# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/subworkflows/yaml-schema.json
name: "get_blobtk_plots"
description: Generate BlobTK plots from a provided Blobtoolkit Dataset
keywords:
  - blobtoolkit
  - plots
  - blobtk
components:
  - blobtk/plot:
      git_remote: https://github.com/nf-core/modules.git

input:
  - fasta:
      type: file
      description: |
        Structure [ val(meta), path(reference) ]
        Meta is the Groovy Map containing sample information
        Reference is the fasta for analysis
  - btk_local_path:
      type: file
      description: |
        Directory of local Blobtoolkit datasets to use for plotting
  - btk_online_path:
      type: string
      description: |
        URL of online Blobtoolkit datasets to use for plotting
  - ch_blobtk_output_format:
      type: string,
      description: |
        Output format for BlobTK plots (png or svg)

output:
  - png_blobtk_images:
      type: file
      description: |
        PNG images generated by BlobTK plots
        Structure: [ val(meta), path(pngs) ]
      pattern: "*.png"
  - svg_blobtk_images:
      type: file
      description: |
        SVG images generated by BlobTK plots
        Structure: [ val(meta), path(svg) ]
      pattern: "*.svg"

authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
