lint:
  files_exist:
    - assets/nf-core-genomenote_logo_light.png
    - docs/images/nf-core-genomenote_logo_light.png
    - docs/images/nf-core-genomenote_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
  files_unchanged:
    - LICENSE
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - lib/NfcoreTemplate.groovy
    - assets/email_template.html
    - .github/CONTRIBUTING.md
    - .github/workflows/branch.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .gitignore
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  template_strings: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: "@priyanka-surana"
  description: Creating standarised genome assembly publications
  force: false
  is_nfcore: false
  name: genomenote
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 2.2.0
