---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: samtools_view
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.21
  # renovate: datasource=conda depName=bioconda/samtools
  - bioconda::samtools=1.20
