contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #genomenote channel"
    url: https://nfcore.slack.com/channels/genomenote
    about: Discussion about the nf-core/genomenote pipeline
