---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.1.3
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-optparse=1.7.3
  - conda-forge::r-scales=1.4.1
